= The Architecture Communication Canvas
Johannes Thorn <Johannes.Thorn@eCube.de>
0.1, November 16, 2023: Ideation
:icons: font
// :noheader:
// :nofooter:

The shortest possible description of your architecture.
For more details see
https://canvas.arc42.org/architecture-communication-canvas[arc42 Architecture Communication Canvas].

[.landscape]
<<<

[.architecture-communication.canvas]
== Architecture Communication Canvas

[.requirement.value-proposition]
.Value Proposition
--
_What is the core business case or economic driver?_
--

[.requirement.key-stakeholder]
.Key Stakeholder
--
* _For whom are we creating value?_
* _Who are the customers?_
* _Who is paying?_
* _Who is contributing?_
--

[.requirement.core-functions]
.Core Functions
--
_Most important functions? +
Supported processes or activities_
--

[.requirement.quality-requirements]
.Quality Requirements
--
_Speed, scalability, reliability, usability, security, safety, capacity, flexibility or similar._
--

[.requirement.business-context]
.Business Context
--
_Important external interfaces or neighboring systems,
including important actors or user roles_
--

[.solution.core-decisions]
.Core Decisions - Good or Bad
--
_Which decisions lead to the current state?_
--

[.solution.components]
.Components/Modules
--
_Major building blocks of the system, important subsystems, modules, services._
--

[.solution.technologies]
.Technologies
--
_Important technologies used for development and operation._
--

[.problem.risks]
.Risks and Missing Information
--
* _Potential problems and risks?_
* _What information is missing or has gotten lost?_
* _What is hindering the team from delivering better value faster?_
--

[.portrait]
<<<

== Explanations

Something important

// technical stuff below

ifdef::backend-html5[]
++++
<style>
.canvas div.sectionbody {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    grid-gap: 10px;
    height: 100%;
}
@media screen {
    .canvas div.sectionbody {
        width: 98vw;
        position: relative;
        left: calc(-49vw + 50%);
    }
}
.canvas div.sectionbody .openblock {
    padding: 20px;
    border-radius: 10px;
    color: #132c15;
}
.canvas div.sectionbody .openblock > .title {
    color: #111111;
    font-size: 1.5em;
}

.requirement {
    background-color: rgb(143, 228, 180);
}
.solution {
    background-color: rgb(148, 215, 239);
}
.problem {
    background-color: rgb(255, 199, 198);
}

.architecture-communication .value-proposition {
    grid-column: 1 / span 1;
    grid-row: 1 / span 2;
}

.architecture-communication .key-stakeholder {
    grid-column: 1 / span 1;
    grid-row: 3 / span 3;
}

.architecture-communication .core-functions {
    grid-column: 2;
    grid-row: 1 / span 3;
}

.architecture-communication .quality-requirements {
    grid-column: 2;
    grid-row: 4 / span 2;
}

.architecture-communication .business-context {
    grid-column: 1 / span 2;
    grid-row: 6 / span 4;
}

.architecture-communication .core-decisions {
    grid-column: 3;
    grid-row: 1 / span 5;
}

.architecture-communication .components {
    grid-column: 3 / span 2;
    grid-row: 6 / span 4;
}

.architecture-communication .technologies {
    grid-column: 4;
    grid-row: 1 / span 5;
}

.architecture-communication .risks {
    grid-column: 1 / span 4;
    grid-row: 10 / span 2;
}

@media print {
    @page {
        size: portrait;
    }
    @page rotated {
        page-orientation: rotate-left;
    }
    div {
        overflow: hidden;
    }
    .sect1.canvas {
        page: rotated;
        transform-origin: top left;
        transform: translateX(100vw) rotate(90deg);
        width: 100vh;
        height: 100vw;
        padding: 0 .9375em !important;
    }
}
</style>
++++
endif::[]
